"""Templates for generating Rust FFI crate files."""

from __future__ import annotations

import re

from sciona.synthesizer.models import AssemblyUnit


def generate_cargo_toml(name: str) -> str:
    """Generate a Cargo.toml for the FFI crate."""
    safe_name = re.sub(r"[^a-zA-Z0-9_-]", "_", name)
    return f"""\
[package]
name = "{safe_name}-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
# build.rs handles linking to the Lean shared library
"""


def generate_build_rs(lean_lib_path: str) -> str:
    """Generate a build.rs that links against the Lean shared library."""
    return f"""\
fn main() {{
    println!("cargo:rustc-link-search=native={lean_lib_path}");
    println!("cargo:rustc-link-lib=dylib=leanshared");
}}
"""


def generate_lib_rs(units: list[AssemblyUnit]) -> str:
    """Generate lib.rs with extern "C" bindings for each assembly unit."""
    lines: list[str] = [
        "//! FFI bindings to verified Lean 4 / Coq definitions.",
        "//!",
        "//! This crate is auto-generated by AGEO-Matcher's extractor.",
        "//! Each function wraps a formally verified definition.",
        "",
        "#![allow(non_camel_case_types)]",
        "",
        "/// Opaque handle to a Lean object managed by the Lean runtime.",
        "#[repr(C)]",
        "pub struct LeanObject {",
        "    _private: [u8; 0],",
        "}",
        "",
    ]

    for unit in units:
        rust_name = _lean_name_to_rust(unit.declaration_name)
        lines.append(f"// Verified definition: {unit.name}")
        lines.append(f"// Lean type: {unit.type_signature}")
        lines.append('extern "C" {')
        lines.append(f"    /// FFI binding to `{unit.declaration_name}`.")
        lines.append(
            f"    pub fn {rust_name}(arg: *mut LeanObject) -> *mut LeanObject;"
        )
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def _lean_name_to_rust(name: str) -> str:
    """Convert a Lean qualified name to a valid Rust identifier."""
    return re.sub(r"[^a-zA-Z0-9_]", "_", name)
