"""Physics knowledge ingestion helpers."""

from sciona.physics_ingest.bindings import (
    BindingDiagnostic,
    BindingResolutionResult,
    resolve_publication_artifact_bindings,
)
from sciona.physics_ingest.cli import (
    REPORT_KIND,
    build_publication_dry_run_report,
    build_publication_dry_run_report_from_payload,
    main,
)
from sciona.physics_ingest.ids import (
    DeterministicIdError,
    attach_deterministic_candidate_ids,
    build_snapshot_id_bindings,
    plan_source_bundle_ids,
    source_candidate_id,
    source_snapshot_id,
    stable_payload_sha256,
)
from sciona.physics_ingest.orchestration import (
    PublicationAuditSummary,
    PublicationOrchestrationResult,
    orchestrate_physics_publication,
)
from sciona.physics_ingest.pdg_cdg import (
    PDGExpressionBinding,
    PDGRelationshipIngestResult,
    build_pdg_relationship_ingest,
)
from sciona.physics_ingest.pipeline import (
    PublicationPipelineResult,
    PublicationPipelineSummary,
    run_physics_publication_pipeline,
)
from sciona.physics_ingest.publication import (
    ArtifactBinding,
    PublicationDiagnostic,
    PublicationLoadResult,
    SymbolicVariableRow,
    ValidityBoundRow,
    load_symbolic_publication_manifest,
)
from sciona.physics_ingest.review import (
    ReviewAssessment,
    ReviewGateResult,
    WORKFLOW_STATUSES,
    assess_publishability,
    require_publishable,
)
from sciona.physics_ingest.retrieval import (
    RawTrustPolicy,
    SymbolicArtifactCandidate,
    SymbolicRankingResult,
    SymbolicRelationship,
    SymbolicRetrievalQuery,
    SymbolicValidityBound,
    candidates_from_rows,
    rank_symbolic_candidates,
    score_symbolic_candidate,
)
from sciona.physics_ingest.staging import (
    ArtifactRelationshipRow,
    PhysicsEquationCandidateRow,
    PhysicsIngestSnapshotRow,
    SymbolicExpressionRow,
    Wave0ContractError,
    attach_snapshot_id,
    stage_source_rows,
    validate_artifact_relationship_row,
    validate_artifact_relationship_rows,
    validate_candidate_row,
    validate_candidate_rows,
    validate_snapshot_row,
    validate_symbolic_expression_row,
)
from sciona.physics_ingest.supabase_adapter import (
    PostgrestPublicationTableClient,
    adapt_publication_supabase_client,
)
from sciona.physics_ingest.write_plan import (
    PublicationWriteBatch,
    PublicationWritePlan,
    PublicationWritePlanAuditSummary,
    build_publication_write_plan,
)
from sciona.physics_ingest.writer import (
    PublicationTableClient,
    PublicationTableWriteResult,
    PublicationWriteDiagnostic,
    PublicationWriteResult,
    PublicationWriter,
    write_publication_rows,
)

__all__ = [
    "ArtifactRelationshipRow",
    "ArtifactBinding",
    "BindingDiagnostic",
    "BindingResolutionResult",
    "DeterministicIdError",
    "PDGExpressionBinding",
    "PDGRelationshipIngestResult",
    "PhysicsEquationCandidateRow",
    "PhysicsIngestSnapshotRow",
    "PublicationAuditSummary",
    "PublicationDiagnostic",
    "PublicationLoadResult",
    "PublicationOrchestrationResult",
    "PublicationPipelineResult",
    "PublicationPipelineSummary",
    "PostgrestPublicationTableClient",
    "PublicationTableClient",
    "PublicationTableWriteResult",
    "PublicationWriteBatch",
    "PublicationWriteDiagnostic",
    "PublicationWritePlan",
    "PublicationWritePlanAuditSummary",
    "PublicationWriteResult",
    "PublicationWriter",
    "ReviewAssessment",
    "ReviewGateResult",
    "RawTrustPolicy",
    "REPORT_KIND",
    "SymbolicArtifactCandidate",
    "SymbolicExpressionRow",
    "SymbolicRankingResult",
    "SymbolicRelationship",
    "SymbolicRetrievalQuery",
    "SymbolicValidityBound",
    "SymbolicVariableRow",
    "ValidityBoundRow",
    "WORKFLOW_STATUSES",
    "Wave0ContractError",
    "adapt_publication_supabase_client",
    "attach_deterministic_candidate_ids",
    "attach_snapshot_id",
    "assess_publishability",
    "build_publication_dry_run_report",
    "build_publication_dry_run_report_from_payload",
    "build_publication_write_plan",
    "build_pdg_relationship_ingest",
    "build_snapshot_id_bindings",
    "candidates_from_rows",
    "load_symbolic_publication_manifest",
    "main",
    "orchestrate_physics_publication",
    "plan_source_bundle_ids",
    "rank_symbolic_candidates",
    "require_publishable",
    "resolve_publication_artifact_bindings",
    "run_physics_publication_pipeline",
    "score_symbolic_candidate",
    "source_candidate_id",
    "source_snapshot_id",
    "stage_source_rows",
    "stable_payload_sha256",
    "validate_artifact_relationship_row",
    "validate_artifact_relationship_rows",
    "validate_candidate_row",
    "validate_candidate_rows",
    "validate_snapshot_row",
    "validate_symbolic_expression_row",
    "write_publication_rows",
]
