{
  "name": "NIGHTCAP",
  "groups": {
    "capnostream": {
      "reader": {
        "fqn": "sciona.principal.adapters.parsers.parse_capnostream_folder",
        "kwargs": {
          "meta": true
        }
      },
      "source": "capnostream",
      "time": "t",
      "properties": {
        "t": {
          "source": "etime",
          "description": "Seconds since epoch for each sample.",
          "transform": {
            "fqn": "sciona.principal.adapters.transforms.shift_time_meta_attr",
            "kwargs": {
              "attr": "capno_shift",
              "meta": true
            }
          }
        },
        "rr": {
          "source": "RR",
          "description": "Respiration rate in breaths per minute."
        },
        "co2": {
          "source": "CO2 Wave",
          "description": "The CO2 wave captured by the sensor."
        },
        "etco2": {
          "source": "EtCO2",
          "description": ""
        },
        "hr": {
          "source": "PR",
          "description": "Pulse rate in BPM."
        },
        "spo2": {
          "source": "SpO2",
          "description": "The SpO2 level measured by the capnostream."
        },
        "spo2_not_available": {
          "source": "SPO2 NOT AVAILABLE",
          "description": "The spo2 is avaialble for use."
        },
        "desat": {
          "source": "DESAT EVENT",
          "description": "An array of desat events."
        }
      }
    },
    "h10_accel": {
      "reader": {
        "fqn": "sciona.principal.adapters.parsers.polar_h10_to_pandas",
        "kwargs": {
          "serial_attr": "polar_serial",
          "only": [
            "ecg",
            "accel",
            "hr",
            "ibi"
          ],
          "meta": true
        },
        "item": "accel"
      },
      "source": "sqlites/*.sqlite",
      "time": "t",
      "properties": {
        "t": {
          "source": "accel_t",
          "description": "Seconds since epoch for each sample UTC."
        },
        "x": {
          "source": "accel_x",
          "description": "Acceleration along the x-axis."
        },
        "y": {
          "source": "accel_y",
          "description": "Acceleration along the y-axis."
        },
        "z": {
          "source": "accel_z",
          "description": "Acceleration along the z-axis."
        }
      }
    },
    "h10_ecg": {
      "reader": {
        "fqn": "sciona.principal.adapters.parsers.polar_h10_to_pandas",
        "kwargs": {
          "serial_attr": "polar_serial",
          "only": [
            "ecg",
            "accel",
            "hr",
            "ibi"
          ],
          "meta": true
        },
        "item": "ecg"
      },
      "source": "sqlites/*.sqlite",
      "time": "t",
      "properties": {
        "t": {
          "source": "ecg_t",
          "description": "Seconds since epoch for each sample UTC."
        },
        "value": {
          "source": "ecg",
          "description": "ECG vector."
        }
      }
    },
    "h10_hr": {
      "reader": {
        "fqn": "sciona.principal.adapters.parsers.polar_h10_to_pandas",
        "kwargs": {
          "serial_attr": "polar_serial",
          "only": [
            "ecg",
            "accel",
            "hr",
            "ibi"
          ],
          "meta": true
        },
        "item": "hr"
      },
      "source": "sqlites/*.sqlite",
      "time": "t",
      "properties": {
        "t": {
          "source": "hr_t",
          "description": "Seconds since epoch for each sample UTC."
        },
        "value": {
          "source": "hr",
          "description": "HR vector."
        }
      }
    },
    "h10_ibi": {
      "reader": {
        "fqn": "sciona.principal.adapters.parsers.polar_h10_to_pandas",
        "kwargs": {
          "serial_attr": "polar_serial",
          "only": [
            "ecg",
            "accel",
            "hr",
            "ibi"
          ],
          "meta": true
        },
        "item": "ibi"
      },
      "source": "sqlites/*.sqlite",
      "time": "t",
      "properties": {
        "t": {
          "source": "ibi_t",
          "description": "Seconds since epoch for each sample UTC."
        },
        "value": {
          "source": "ibi",
          "description": "IBI vector."
        }
      }
    }
  },
  "meta": {
    "source": "tracker_single.csv",
    "reader": {
      "fqn": "pandas.read_csv"
    },
    "hpysource": "research",
    "per": false,
    "day": {
      "source": "session_date",
      "ftime": "%m/%d/%Y"
    },
    "serial": {
      "source": "ring_serial_1"
    },
    "user": {
      "source": "study_id"
    },
    "folder": {
      "source": "trial_name"
    },
    "tz": {
      "source": "timezone"
    },
    "other": [
      {
        "name": "capno_shift",
        "description": "Time shift in seconds to align capnostream data with everything else."
      },
      {
        "name": "mighty_shift",
        "description": "Time shift in seconds to align Happy Ring 1 data with everything else."
      },
      {
        "name": "polar_serial",
        "description": "H10 serial number."
      }
    ]
  }
}
