{
  "name": "NIGHTCAP",
  "groups": {
    "h10_ecg": {
      "reader": {
        "fqn": "sciona.principal.adapters.parsers.polar_h10_to_pandas",
        "kwargs": {
          "serial_attr": "polar_serial",
          "only": [
            "ecg",
            "accel",
            "hr",
            "ibi"
          ],
          "meta": true
        },
        "item": "ecg"
      },
      "source": "sqlites/*.sqlite",
      "time": "t",
      "properties": {
        "t": {
          "source": "ecg_t",
          "description": "Seconds since epoch for each sample UTC."
        },
        "value": {
          "source": "ecg",
          "description": "ECG vector."
        }
      }
    }
  },
  "meta": {
    "source": "tracker_single.csv",
    "reader": {
      "fqn": "pandas.read_csv"
    },
    "hpysource": "research",
    "per": false,
    "day": {
      "source": "session_date",
      "ftime": "%m/%d/%Y"
    },
    "serial": {
      "source": "ring_serial_1"
    },
    "user": {
      "source": "study_id"
    },
    "folder": {
      "source": "trial_name"
    },
    "tz": {
      "source": "timezone"
    },
    "other": [
      {
        "name": "capno_shift",
        "description": "Time shift in seconds to align capnostream data with everything else."
      },
      {
        "name": "mighty_shift",
        "description": "Time shift in seconds to align Happy Ring 1 data with everything else."
      },
      {
        "name": "polar_serial",
        "description": "H10 serial number."
      }
    ]
  }
}
