sources:
  - name: sciona-atoms-signal-processing
    path: ../sciona-atoms
    python_path: src
    package: sciona.atoms.signal_processing.biosppy
  - name: sciona-atoms-state-estimation
    path: ../sciona-atoms
    python_path: src
    package: sciona.atoms.state_estimation
  - name: sciona-atoms-algorithmic
    path: ../sciona-atoms
    python_path: src
    package: sciona.atoms.algorithmic.divide_and_conquer
  - name: ageo-atoms
    path: ../ageo-atoms
    package: ageoa
