sources:
  - name: sciona-atoms-signal-processing
    path: ../sciona-atoms
    python_path: src
    package: sciona.atoms.signal_processing.biosppy
  - name: sciona-atoms-state-estimation
    path: ../sciona-atoms
    python_path: src
    package: sciona.atoms.state_estimation.kalman_filters
  - name: ageo-atoms
    path: ../ageo-atoms
    package: ageoa
