"""Public computational defaults pinned to Contrails winning source."""
from copy import deepcopy

_DEFAULTS = {'single': {'model': {'encoder': 'maxvit_tiny_tf_512.in1k',
                      'pretrained': True,
                      'decoder_channels': [256, 128, 64, 32, 16],
                      'load': None,
                      'dropout': 0.0},
            'train': {'weight_decay': '1e-4',
                      'batch_size': 4,
                      'accumulate': 2,
                      'num_workers': 2,
                      'loss': 'bce'},
            'data': {'resize': 1024,
                     'annotation_mean': True,
                     'augment': 'rotation',
                     'augment_prob': 0.95,
                     'positive_only': False,
                     'y_sym_mode': 'bilinear'},
            'val': {'per_epoch': 1, 'th': 0.45},
            'test': {'th': 0.45},
            'scheduler': [{'linear': {'lr_start': '1e-8',
                                      'lr_end': '8e-4',
                                      'epoch_end': 0.5}},
                          {'cosine': {'lr_end': '1e-6', 'epoch_end': 35}}]},
 'temporal': {'model': {'encoder': 'maxvit_tiny_tf_512.in1k',
                        'pretrained': True,
                        'decoder_channels': [256, 128, 64, 32, 32],
                        'load': None,
                        'dropout': 0.0},
              'train': {'weight_decay': '1e-2',
                        'batch_size': 4,
                        'accumulate': 2,
                        'num_workers': 2,
                        'loss': 'bce',
                        'checkpoint': False},
              'data': {'resize': 512,
                       'annotation_mean': True,
                       'augment': 'rotation',
                       'augment_prob': 0.95,
                       'positive_only': False,
                       'y_sym_mode': 'bilinear'},
              'val': {'per_epoch': 1, 'th': 0.45},
              'test': {'th': 0.45},
              'scheduler': [{'linear': {'lr_start': '1e-8',
                                        'lr_end': '8e-4',
                                        'epoch_end': 0.5}},
                            {'cosine': {'lr_end': '1e-6', 'epoch_end': 40}}]}}

def defaults():
    return deepcopy(_DEFAULTS)
