"""Source adapters for physics knowledge ingestion."""

from sciona.physics_ingest.sources.adapter_coverage import (
    SourceAdapterCoverageDiagnostic,
    SourceAdapterCoverageJob,
    SourceAdapterCoverageReport,
    build_source_adapter_coverage_report,
    build_source_adapter_coverage_report_dict,
)
from sciona.physics_ingest.sources.execution_plan import (
    SourceExecutionDiagnostic,
    SourceExecutionReadinessReport,
    SourceExecutionReadinessStep,
    build_source_execution_readiness_report,
    build_source_execution_readiness_report_dict,
)
from sciona.physics_ingest.sources.executor import (
    SourceRetrievalExecutionReport,
    SourceRetrievalExecutionResult,
    execute_source_retrieval_plan,
    execute_source_retrieval_plan_dict,
)
from sciona.physics_ingest.sources.local_runtime import (
    LocalFilesystemSnapshotSink,
    UrllibSourceHTTPClient,
    UrllibSourceHTTPResponse,
)
from sciona.physics_ingest.sources.retrieval_plan import (
    PHASE7_RING_ORDER,
    PaginationSpec,
    RateLimitHint,
    RetrievalEndpoint,
    RetrievalJob,
    RetrievalRunDiagnostic,
    RetrievalRunPlan,
    RetrievalRunStep,
    RetryPolicy,
    SourceRetrievalManifest,
    build_physics_source_retrieval_manifest,
    build_physics_source_retrieval_manifest_dict,
    build_physics_source_retrieval_run_plan,
    build_physics_source_retrieval_run_plan_dict,
)
from sciona.physics_ingest.sources.runtime_adapters import (
    SourceRetrievalHTTPAdapter,
    SourceRetrievalRuntimeAdapterBundle,
    SourceRetrievalRuntimeAdapterReport,
    SourceRetrievalSnapshotSinkAdapter,
    build_source_retrieval_runtime_adapter_report,
    build_source_retrieval_runtime_adapters,
)
from sciona.physics_ingest.sources.runtime_execution import (
    SourceRetrievalRuntimeExecutionDiagnostic,
    SourceRetrievalRuntimeExecutionReport,
    SourceRetrievalRuntimeExecutionStep,
    build_source_retrieval_runtime_execution_report,
    build_source_retrieval_runtime_execution_report_dict,
)

__all__ = [
    "PHASE7_RING_ORDER",
    "PaginationSpec",
    "RateLimitHint",
    "RetrievalEndpoint",
    "RetrievalJob",
    "RetrievalRunDiagnostic",
    "RetrievalRunPlan",
    "RetrievalRunStep",
    "RetryPolicy",
    "LocalFilesystemSnapshotSink",
    "SourceAdapterCoverageDiagnostic",
    "SourceAdapterCoverageJob",
    "SourceAdapterCoverageReport",
    "SourceExecutionDiagnostic",
    "SourceExecutionReadinessReport",
    "SourceExecutionReadinessStep",
    "SourceRetrievalHTTPAdapter",
    "SourceRetrievalExecutionReport",
    "SourceRetrievalExecutionResult",
    "SourceRetrievalManifest",
    "SourceRetrievalRuntimeAdapterBundle",
    "SourceRetrievalRuntimeAdapterReport",
    "SourceRetrievalRuntimeExecutionDiagnostic",
    "SourceRetrievalRuntimeExecutionReport",
    "SourceRetrievalRuntimeExecutionStep",
    "SourceRetrievalSnapshotSinkAdapter",
    "UrllibSourceHTTPClient",
    "UrllibSourceHTTPResponse",
    "build_physics_source_retrieval_manifest",
    "build_physics_source_retrieval_manifest_dict",
    "build_physics_source_retrieval_run_plan",
    "build_physics_source_retrieval_run_plan_dict",
    "build_source_adapter_coverage_report",
    "build_source_adapter_coverage_report_dict",
    "build_source_execution_readiness_report",
    "build_source_execution_readiness_report_dict",
    "build_source_retrieval_runtime_adapter_report",
    "build_source_retrieval_runtime_adapters",
    "build_source_retrieval_runtime_execution_report",
    "build_source_retrieval_runtime_execution_report_dict",
    "execute_source_retrieval_plan",
    "execute_source_retrieval_plan_dict",
]
